services:
  frontend:
    
      
    ports:
      - "5173:5173"
    image: yashpatil16/mernfrontend:${FRONTEND_IMAGE}
    networks:
      - mern
    
   

  backend:
    
      
    ports:
      - "5050:5050"
    image: yashpatil16/mernbackend:${BACKEND_IMAGE}
    networks:
      - mern
    

    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mern
    volumes:
      - mongo-data:/data/db

networks:
  mern:
    driver: bridge

volumes:
  mongo-data:
    driver: local
 
 
    